src/Entity/Driver.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DriverRepository")
 */
class Driver
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone_number;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Rental", mappedBy="driver")
     */
    private $vehicule;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Rental", mappedBy="driver")
     */
    private $rentals;

    public function __construct()
    {
        $this->vehicule = new ArrayCollection();
        $this->rentals = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    /**
     * @return Collection|Rental[]
     */
    public function getVehicule(): Collection
    {
        return $this->vehicule;
    }

    public function addVehicule(Rental $vehicule): self
    {
        if (!$this->vehicule->contains($vehicule)) {
            $this->vehicule[] = $vehicule;
            $vehicule->setDriver($this);
        }

        return $this;
    }

    public function removeVehicule(Rental $vehicule): self
    {
        if ($this->vehicule->contains($vehicule)) {
            $this->vehicule->removeElement($vehicule);
            // set the owning side to null (unless already changed)
            if ($vehicule->getDriver() === $this) {
                $vehicule->setDriver(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Rental[]
     */
    public function getRentals(): Collection
    {
        return $this->rentals;
    }

    public function addRental(Rental $rental): self
    {
        if (!$this->rentals->contains($rental)) {
            $this->rentals[] = $rental;
            $rental->setDriver($this);
        }

        return $this;
    }

    public function removeRental(Rental $rental): self
    {
        if ($this->rentals->contains($rental)) {
            $this->rentals->removeElement($rental);
            // set the owning side to null (unless already changed)
            if ($rental->getDriver() === $this) {
                $rental->setDriver(null);
            }
        }

        return $this;
    }
}

src/Form/DriverType.php
<?php

namespace App\Form;

use App\Entity\Driver;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DriverType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname')
            ->add('lastname')
            ->add('phone_number')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Driver::class,
        ]);
    }
}

src/Controller/DriverController.php
<?php

namespace App\Controller;

use App\Entity\Driver;
use App\Form\DriverType;
use App\Repository\DriverRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/driver")
 */
class DriverController extends AbstractController
{
    /**
     * @Route("/", name="driver_index", methods={"GET"})
     */
    public function index(DriverRepository $driverRepository, Request $request): Response

        /**
         * @Route("/{id}/edit",name="driver_edit")
         *
         */
    {
        $results=null;
        $driverSearch=$request->request->get('driver_search');

        if($driverSearch)
        {
            $results=$driverRepository->findByNameOrTel($driverSearch);
        }
        else{
            $results=$driverRepository->findAll();
        }
        //on renvoie vers l'index
        return $this->render('driver/index.html.twig', [
            'drivers' => $results
        ]);
    }


    /**
     * @Route("/new", name="driver_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $driver = new Driver();
        $form = $this->createForm(DriverType::class, $driver);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($driver);
            $entityManager->flush();

            return $this->redirectToRoute('driver_index');
        }

        return $this->render('driver/new.html.twig', [
            'driver' => $driver,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="driver_show", methods={"GET"})
     */
    public function show(Driver $driver): Response
    {
        return $this->render('driver/show.html.twig', [
            'driver' => $driver,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="driver_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Driver $driver): Response
    {
        $form = $this->createForm(DriverType::class, $driver);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('driver_index');
        }

        return $this->render('driver/edit.html.twig', [
            'driver' => $driver,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="driver_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Driver $driver): Response
    {
        if ($this->isCsrfTokenValid('deleteDriver'.$driver->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($driver);
            $entityManager->flush();
        }

        return $this->redirectToRoute('driver_index');
    }
}

templates/driver/_delete_form.html.twig
<form method="post" action="{{ path('driver_delete', {'id': driver.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ driver.id) }}">
    <button class="btn">Delete</button>
</form>

templates/driver/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/driver/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Driver{% endblock %}

{% block body %}
    <h1>Edit Driver</h1>

    {{ include('driver/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('driver_index') }}">back to list</a>

    {{ include('driver/_delete_form.html.twig') }}
{% endblock %}

templates/driver/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Driver index{% endblock %}

{% block body %}
    <h1>Driver index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Phone_number</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for driver in drivers %}
            <tr>
                <td>{{ driver.id }}</td>
                <td>{{ driver.firstname }}</td>
                <td>{{ driver.lastname }}</td>
                <td>{{ driver.phoneNumber }}</td>
                <td>
                    <a href="{{ path('driver_show', {'id': driver.id}) }}">show</a>
                    <a href="{{ path('driver_edit', {'id': driver.id}) }}">edit</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('driver_new') }}">Create new</a>
{% endblock %}

templates/driver/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Driver{% endblock %}

{% block body %}
    <h1>Create new Driver</h1>

    {{ include('driver/_form.html.twig') }}

    <a href="{{ path('driver_index') }}">back to list</a>
{% endblock %}

templates/driver/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Driver{% endblock %}

{% block body %}
    <h1>Driver</h1>

    {% for driver in drivers %}

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ driver.id }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ driver.firstname }}</td>
            </tr>
            <tr>
                <th>Lastname</th>
                <td>{{ driver.lastname }}</td>
            </tr>
            <tr>
                <th>Phone_number</th>
                <td>{{ driver.phoneNumber }}</td>
            </tr>

        <div class="card-footer">
                <a class="btn btn-sm btn-warning" href="{{ path('driver_edit', {id: driver.id}) }}">Éditer</a>
                <form method="post" action="{{ path('driver_delete', { id: driver.id }) }}">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('deleteDriver' ~ driver.id) }}">
                    <button class="btn btn-sm btn-danger" style="margin-top:1px; margin-left:5px;">Supprimer</button>
                </form>
        </div>

        </tbody>
    </table>

    <a href="{{ path('driver_index') }}">back to list</a>

    <a href="{{ path('driver_edit', {'id': driver.id}) }}">edit</a>

    {{ include('driver/_delete_form.html.twig') }}

    {% endfor %}
{% endblock %}